export const COURSE_CATEGORIES = [
  { label: '全部', value: 'all' },
  { label: '公共课', value: 'public' },
  { label: '专业课', value: 'major' },
]

export const COURSES = [
  {
    id: 1,
    subject: '大学英语',
    category: '公共课',
    name: '专升本大学英语精讲班',
    desc: '从词汇到写作，系统性提升英语综合能力，紧扣广西专升本英语考纲',
    teacher: '张雪峰教授',
    students: 3256,
    rating: 4.9,
    price: 299,
    hot: true,
    color: 'linear-gradient(135deg, #e8f3ff, #d0e6ff)',
    duration: '12周',
    lessons: 48,
  },
  {
    id: 2,
    subject: '高等数学',
    category: '公共课',
    name: '专升本高等数学强化班',
    desc: '聚焦必考知识点，精讲精练，帮助零基础学员快速突破数学难关',
    teacher: '李明博士',
    students: 2187,
    rating: 4.8,
    price: 359,
    hot: true,
    color: 'linear-gradient(135deg, #fff3e8, #ffe6d0)',
    duration: '10周',
    lessons: 40,
  },
  {
    id: 3,
    subject: '管理学',
    category: '专业课',
    name: '管理学原理精讲精练',
    desc: '结合广西专升本管理学考纲，深入浅出讲解管理理论与实践案例',
    teacher: '王红副教授',
    students: 1876,
    rating: 4.7,
    price: 259,
    hot: false,
    color: 'linear-gradient(135deg, #f0ffe8, #d8ffc0)',
    duration: '8周',
    lessons: 32,
  },
  {
    id: 4,
    subject: '大学语文',
    category: '公共课',
    name: '专升本大学语文基础班',
    desc: '从文言文到现代文阅读，全面提升语文素养与应试技巧',
    teacher: '刘芳教授',
    students: 1567,
    rating: 4.8,
    price: 199,
    hot: false,
    color: 'linear-gradient(135deg, #f3e8ff, #e0d0ff)',
    duration: '10周',
    lessons: 36,
  },
  {
    id: 5,
    subject: '会计学',
    category: '专业课',
    name: '会计学基础与实务',
    desc: '理论联系实际，掌握会计核心技能，轻松应对专业考试',
    teacher: '陈强讲师',
    students: 1342,
    rating: 4.6,
    price: 279,
    hot: false,
    color: 'linear-gradient(135deg, #e8ffee, #c0ffd8)',
    duration: '8周',
    lessons: 30,
  },
  {
    id: 6,
    subject: '计算机',
    category: '专业课',
    name: '计算机应用基础速成班',
    desc: '零基础入门，涵盖Office操作与计算机基础理论，快速提分',
    teacher: '赵敏博士',
    students: 2103,
    rating: 4.7,
    price: 239,
    hot: false,
    color: 'linear-gradient(135deg, #fff0e8, #ffe0c8)',
    duration: '6周',
    lessons: 24,
  },
  {
    id: 7,
    subject: '政治',
    category: '公共课',
    name: '专升本政治理论精讲班',
    desc: '紧扣时事热点，系统梳理政治理论考点，助力高分突破',
    teacher: '周华教授',
    students: 2890,
    rating: 4.9,
    price: 269,
    hot: true,
    color: 'linear-gradient(135deg, #fff8e8, #ffeecc)',
    duration: '8周',
    lessons: 32,
  },
  {
    id: 8,
    subject: '经济学',
    category: '专业课',
    name: '经济学原理与实务',
    desc: '宏观微观经济学核心知识详解，配合同步习题巩固提升',
    teacher: '吴芳博士',
    students: 987,
    rating: 4.5,
    price: 289,
    hot: false,
    color: 'linear-gradient(135deg, #e8f5ff, #cce5ff)',
    duration: '10周',
    lessons: 36,
  },
]
