export const COURSE_CATEGORIES = [
  { label: '全部', value: 'all' },
  { label: '公共课', value: 'public' },
  { label: '专业课', value: 'major' },
]

// ========== 一级学科大类（首屏卡片） ==========
export const SUBJECT_CATEGORIES = [
  {
    key: 'yuwen',
    name: '语文',
    icon: '📖',
    color: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    desc: '文言文 · 现代文阅读 · 写作',
    subjects: ['大学语文'],
  },
  {
    key: 'shuxue',
    name: '数学',
    icon: '📐',
    color: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    desc: '函数 · 微积分 · 线性代数',
    subjects: ['高等数学'],
  },
  {
    key: 'yingyu',
    name: '英语',
    icon: '🌍',
    color: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    desc: '词汇 · 语法 · 阅读 · 写作',
    subjects: ['大学英语'],
  },
  {
    key: 'zhuanyeke',
    name: '专业课',
    icon: '📚',
    color: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    desc: '管理 · 会计 · 计算机 · 经济',
    subjects: ['管理学', '会计学', '计算机', '经济学', '政治'],
  },
]

// ========== 专业课教材配图（书本实拍 / 封面图） ==========
export const PROFESSIONAL_BOOKS = {
  '管理学': { cover: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect fill="#2c3e50" width="200" height="260" rx="8"/><rect fill="#34495e" x="12" y="12" width="176" height="236" rx="4"/><text x="100" y="100" text-anchor="middle" fill="#ecf0f1" font-size="20" font-weight="bold">管理学</text><text x="100" y="130" text-anchor="middle" fill="#bdc3c7" font-size="14">原理与实务</text><rect fill="#e74c3c" x="60" y="160" width="80" height="4" rx="2"/><text x="100" y="200" text-anchor="middle" fill="#95a5a6" font-size="11">专升本指定教材</text></svg>'), price: '¥45.00' },
  '会计学': { cover: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect fill="#1a5276" width="200" height="260" rx="8"/><rect fill="#2471a3" x="12" y="12" width="176" height="236" rx="4"/><text x="100" y="100" text-anchor="middle" fill="#ebf5fb" font-size="20" font-weight="bold">会计学</text><text x="100" y="130" text-anchor="middle" fill="#aed6f1" font-size="14">基础与实务</text><rect fill="#f39c12" x="60" y="160" width="80" height="4" rx="2"/><text x="100" y="200" text-anchor="middle" fill="#85c1e9" font-size="11">专升本指定教材</text></svg>'), price: '¥42.00' },
  '计算机': { cover: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect fill="#1b4f72" width="200" height="260" rx="8"/><rect fill="#2e86c1" x="12" y="12" width="176" height="236" rx="4"/><text x="100" y="100" text-anchor="middle" fill="#d6eaf8" font-size="20" font-weight="bold">计算机</text><text x="100" y="130" text-anchor="middle" fill="#aed6f1" font-size="14">应用基础</text><rect fill="#27ae60" x="60" y="160" width="80" height="4" rx="2"/><text x="100" y="200" text-anchor="middle" fill="#85c1e9" font-size="11">专升本指定教材</text></svg>'), price: '¥39.00' },
  '经济学': { cover: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect fill="#7d3c98" width="200" height="260" rx="8"/><rect fill="#9b59b6" x="12" y="12" width="176" height="236" rx="4"/><text x="100" y="100" text-anchor="middle" fill="#f5eef8" font-size="20" font-weight="bold">经济学</text><text x="100" y="130" text-anchor="middle" fill="#d2b4de" font-size="14">原理与实务</text><rect fill="#e67e22" x="60" y="160" width="80" height="4" rx="2"/><text x="100" y="200" text-anchor="middle" fill="#d2b4de" font-size="11">专升本指定教材</text></svg>'), price: '¥46.00' },
  '政治': { cover: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260"><rect fill="#922b21" width="200" height="260" rx="8"/><rect fill="#c0392b" x="12" y="12" width="176" height="236" rx="4"/><text x="100" y="100" text-anchor="middle" fill="#fadbd8" font-size="20" font-weight="bold">政治</text><text x="100" y="130" text-anchor="middle" fill="#f1948a" font-size="14">理论精讲</text><rect fill="#f1c40f" x="60" y="160" width="80" height="4" rx="2"/><text x="100" y="200" text-anchor="middle" fill="#f1948a" font-size="11">专升本指定教材</text></svg>'), price: '¥38.00' },
}

export const COURSES = [
  {
    id: 1,
    subject: '大学英语',
    category: '公共课',
    name: '专升本大学英语精讲班',
    desc: '从词汇到写作，系统性提升英语综合能力，紧扣广西专升本英语考纲',
    teacher: '张雪峰教授',
    students: 3256,
    rating: 4.9,
    price: 299,
    hot: true,
    color: 'linear-gradient(135deg, #e8f3ff, #d0e6ff)',
    duration: '12周',
    lessons: 48,
  },
  {
    id: 2,
    subject: '高等数学',
    category: '公共课',
    name: '专升本高等数学强化班',
    desc: '聚焦必考知识点，精讲精练，帮助零基础学员快速突破数学难关',
    teacher: '李明博士',
    students: 2187,
    rating: 4.8,
    price: 359,
    hot: true,
    color: 'linear-gradient(135deg, #fff3e8, #ffe6d0)',
    duration: '10周',
    lessons: 40,
  },
  {
    id: 3,
    subject: '管理学',
    category: '专业课',
    name: '管理学原理精讲精练',
    desc: '结合广西专升本管理学考纲，深入浅出讲解管理理论与实践案例',
    teacher: '王红副教授',
    students: 1876,
    rating: 4.7,
    price: 259,
    hot: false,
    color: 'linear-gradient(135deg, #f0ffe8, #d8ffc0)',
    duration: '8周',
    lessons: 32,
  },
  {
    id: 4,
    subject: '大学语文',
    category: '公共课',
    name: '专升本大学语文基础班',
    desc: '从文言文到现代文阅读，全面提升语文素养与应试技巧',
    teacher: '刘芳教授',
    students: 1567,
    rating: 4.8,
    price: 199,
    hot: false,
    color: 'linear-gradient(135deg, #f3e8ff, #e0d0ff)',
    duration: '10周',
    lessons: 36,
  },
  {
    id: 5,
    subject: '会计学',
    category: '专业课',
    name: '会计学基础与实务',
    desc: '理论联系实际，掌握会计核心技能，轻松应对专业考试',
    teacher: '陈强讲师',
    students: 1342,
    rating: 4.6,
    price: 279,
    hot: false,
    color: 'linear-gradient(135deg, #e8ffee, #c0ffd8)',
    duration: '8周',
    lessons: 30,
  },
  {
    id: 6,
    subject: '计算机',
    category: '专业课',
    name: '计算机应用基础速成班',
    desc: '零基础入门，涵盖Office操作与计算机基础理论，快速提分',
    teacher: '赵敏博士',
    students: 2103,
    rating: 4.7,
    price: 239,
    hot: false,
    color: 'linear-gradient(135deg, #fff0e8, #ffe0c8)',
    duration: '6周',
    lessons: 24,
  },
  {
    id: 7,
    subject: '政治',
    category: '公共课',
    name: '专升本政治理论精讲班',
    desc: '紧扣时事热点，系统梳理政治理论考点，助力高分突破',
    teacher: '周华教授',
    students: 2890,
    rating: 4.9,
    price: 269,
    hot: true,
    color: 'linear-gradient(135deg, #fff8e8, #ffeecc)',
    duration: '8周',
    lessons: 32,
  },
  {
    id: 8,
    subject: '经济学',
    category: '专业课',
    name: '经济学原理与实务',
    desc: '宏观微观经济学核心知识详解，配合同步习题巩固提升',
    teacher: '吴芳博士',
    students: 987,
    rating: 4.5,
    price: 289,
    hot: false,
    color: 'linear-gradient(135deg, #e8f5ff, #cce5ff)',
    duration: '10周',
    lessons: 36,
  },
]

export const TOPICS_MAP = {
  '大学英语': ['词汇积累与记忆法', '语法核心精讲', '阅读理解技巧突破', '翻译实战训练', '写作模板与范文', '听力专项提升', '真题模拟与解析', '考前冲刺串讲'],
  '高等数学': ['函数与极限', '导数与微分', '不定积分', '定积分及应用', '微分方程', '向量与空间几何', '多元函数微分', '重积分与曲线积分'],
  '管理学': ['管理概述与理论发展', '决策与计划', '组织设计与文化', '领导与激励', '控制与绩效评估', '管理案例分析', '模拟测试(一)', '模拟测试(二)'],
  '大学语文': ['文言文基础知识', '诗词鉴赏方法', '现代文阅读技巧', '作文立意与结构', '文学常识汇总', '历年真题精讲', '考场应试策略', '综合模拟卷'],
  '会计学': ['会计基础概念', '复式记账法', '会计凭证与账簿', '财务报表编制', '成本计算方法', '财务分析技巧', '实务操作模拟', '考前总复习'],
  '计算机': ['计算机基础知识', 'Windows操作系统', 'Word文档处理', 'Excel电子表格', 'PowerPoint演示', '网络与安全基础', '上机实操训练', '综合测试'],
  '政治': ['马克思主义哲学', '政治经济学原理', '毛泽东思想', '中国特色社会主义', '时事政治热点', '道德与法律基础', '真题解析(一)', '真题解析(二)'],
  '经济学': ['需求与供给理论', '消费者行为分析', '生产与成本理论', '市场结构分析', '宏观经济学基础', '货币与金融体系', '经济政策解读', '综合复习与测试'],
}
