// ========== 刷题 & 资源讨论专区 ==========

/** 板块分类 */
export const BOARD_CATEGORIES = [
  { id: 'quantao', icon: '🧠', name: '全科讨论', desc: '各科目综合交流', color: '#2a6eff' },
  { id: 'english', icon: '🔤', name: '大学英语', desc: '语法词汇阅读写作', color: '#4caf50' },
  { id: 'math', icon: '📐', name: '高等数学', desc: '微积分线性代数概率', color: '#ff6b35' },
  { id: 'chinese', icon: '📚', name: '大学语文', desc: '文学常识古文阅读', color: '#9c27b0' },
  { id: 'politics', icon: '📋', name: '政治理论', desc: '毛概思修马原', color: '#e74c3c' },
  { id: 'resource', icon: '📦', name: '资源分享', desc: '资料真题笔记共享', color: '#008888' },
]

/** 帖子列表 */
export const MOCK_POSTS = [
  {
    id: 1,
    board: 'quantao',
    title: '24年专升本备考经验分享，从零基础到上岸全记录',
    author: { name: '桂小升', avatar: '桂', color: '#2a6eff' },
    tags: ['经验分享', '备考计划'],
    createdAt: '2024-06-15',
    replyCount: 42,
    viewCount: 3250,
    pinned: true,
    content: '大家好，我是今年上岸的学长。在这里想分享一下我的备考经验……\n\n第一阶段（7-9月）：基础夯实\n每天坚持背单词、看网课，把各科基础知识点过一遍。\n\n第二阶段（10-12月）：专项突破\n重点刷题，特别是高数和英语，每天至少做2套试卷。\n\n第三阶段（1-3月）：冲刺模拟\n严格按照考试时间做真题模拟，查漏补缺。',
  },
  {
    id: 2,
    board: 'quantao',
    title: '有没有一起组队刷题的小伙伴？互相监督打卡',
    author: { name: '升本冲冲冲', avatar: '冲', color: '#ff6b35' },
    tags: ['组队', '打卡'],
    createdAt: '2024-08-20',
    replyCount: 28,
    viewCount: 1890,
    pinned: false,
    content: '一个人刷题总是坚持不下来，想找个学习搭子互相监督。\n目前进度：英语词汇背完一轮，高数第三章，语文古诗词背了一半。\n有差不多进度的同学一起吗？',
  },
  {
    id: 3,
    board: 'english',
    title: '英语阅读理解总是做不完怎么办？求高效解题方法',
    author: { name: '英语小菜鸟', avatar: '英', color: '#4caf50' },
    tags: ['英语', '阅读技巧'],
    createdAt: '2024-09-01',
    replyCount: 35,
    viewCount: 2650,
    pinned: false,
    content: '每次做阅读理解都要花40多分钟，导致后面作文来不及写。请问各位大佬有什么提速技巧吗？\n\n我目前的方法是先看题目再读文章，但还是很慢……',
  },
  {
    id: 4,
    board: 'math',
    title: '高数第七章不定积分，这几个题型一直搞不懂，求大佬指教',
    author: { name: '数学好难', avatar: '数', color: '#ff6b35' },
    tags: ['高数', '不定积分', '求助'],
    createdAt: '2024-08-28',
    replyCount: 56,
    viewCount: 4200,
    pinned: true,
    content: '换元积分法和分部积分法经常搞混，做题的时候总是选不对方法。\n\n附上几道我经常做错的题目，麻烦大佬帮忙分析一下思路……',
  },
  {
    id: 5,
    board: 'resource',
    title: '[资料分享] 2020-2024年广西专升本全套真题PDF，需要的自取',
    author: { name: '资源达人', avatar: '资', color: '#008888' },
    tags: ['真题', 'PDF', '免费分享'],
    createdAt: '2024-09-05',
    replyCount: 128,
    viewCount: 8600,
    pinned: true,
    content: '整理了很久的五年真题合集，包含答案解析。\n\n链接在评论区一楼，需要的同学自取。\n如果觉得有用记得点赞支持一下~',
  },
  {
    id: 6,
    board: 'chinese',
    title: '大学语文必背古诗词60首，分享我的背诵技巧',
    author: { name: '文学爱好者', avatar: '文', color: '#9c27b0' },
    tags: ['语文', '古诗词', '记忆方法'],
    createdAt: '2024-07-15',
    replyCount: 89,
    viewCount: 5600,
    pinned: false,
    content: '古诗词背诵不要死记硬背，分享一下我的三步法：\n1. 先了解作者背景和创作背景\n2. 逐句理解诗意，画出思维导图\n3. 利用碎片时间反复朗读\n\n具体每首诗的导图我整理在下面了……',
  },
  {
    id: 7,
    board: 'politics',
    title: '政治大题答题模板整理，背完这些上考场不慌',
    author: { name: '政治高分选手', avatar: '政', color: '#e74c3c' },
    tags: ['政治', '答题模板', '干货'],
    createdAt: '2024-09-10',
    replyCount: 204,
    viewCount: 12300,
    pinned: false,
    content: '政治大题其实有套路可循，我总结了几个万能答题模板：\n\n一、"是什么-为什么-怎么办"三段式\n二、结合材料分析法\n三、时政热点关联法\n\n详细模板见下方……',
  },
  {
    id: 8,
    board: 'quantao',
    title: '专升本和直接就业怎么选？大二学生在线迷茫',
    author: { name: '迷茫的大二', avatar: '迷', color: '#607d8b' },
    tags: ['职业规划', '迷茫'],
    createdAt: '2024-09-15',
    replyCount: 66,
    viewCount: 4800,
    pinned: false,
    content: '现在大二下学期了，很纠结要不要专升本。\n一方面想提升学历，另一方面又怕考不上浪费时间。\n有过来人给点建议吗？',
  },
]

/** 楼层回复 */
export const MOCK_REPLIES = [
  {
    id: 101,
    postId: 1,
    floor: 1,
    author: { name: '上岸学姐', avatar: '学', color: '#9c27b0' },
    content: '恭喜学弟上岸！补充一下：英语单词一定要每天坚持背，我用的是墨墨背单词，效果很好。',
    createdAt: '2024-06-15',
    likes: 24,
  },
  {
    id: 102,
    postId: 1,
    floor: 2,
    author: { name: '大二备考生', avatar: '备', color: '#ff9800' },
    content: '请问高数部分有没有推荐的网课老师？',
    createdAt: '2024-06-16',
    likes: 8,
  },
  {
    id: 103,
    postId: 1,
    floor: 3,
    author: { name: '桂小升', avatar: '桂', color: '#2a6eff' },
    content: '回复2楼：高数我推荐张宇老师的基础班，讲得很细致，适合零基础。线代可以看李永乐。',
    createdAt: '2024-06-16',
    likes: 15,
  },
  {
    id: 104,
    postId: 5,
    floor: 1,
    author: { name: '资源达人', avatar: '资', color: '#008888' },
    content: '真题链接：https://pan.example.com/gxzsb （提取码：gxzs）\n\n2020-2024年共5年真题，含详细答案解析。如果链接失效请私信我。',
    createdAt: '2024-09-05',
    likes: 86,
  },
  {
    id: 105,
    postId: 5,
    floor: 2,
    author: { name: '感谢分享', avatar: '谢', color: '#4caf50' },
    content: '太感谢了！找了好久终于找到完整的真题了，已收藏！',
    createdAt: '2024-09-05',
    likes: 32,
  },
]