// ========== 备考资料库专区 ==========

export const RESOURCE_SECTIONS = [
  {
    id: 'syllabus',
    title: '专升本考试大纲',
    icon: '📋',
    desc: '权威官方考纲解读，明确复习方向',
    color: '#2a6eff',
  },
  {
    id: 'library',
    title: '电子资源文库',
    icon: '📚',
    desc: '真题试卷 × 模拟试题 × 学霸笔记',
    color: '#9c27b0',
  },
  {
    id: 'knowledge',
    title: '核心知识点梳理',
    icon: '🧩',
    desc: '按学科分类的知识精华，高效记忆',
    color: '#ff6b35',
  },
]

/** 考试大纲资料 */
export const SYLLABUS_ITEMS = [
  {
    id: 1,
    subject: '大学英语',
    icon: '🔤',
    color: '#2a6eff',
    title: '大学英语考试大纲（2024版）',
    desc: '含词汇要求、语法范围、题型分布、分值比例等完整考纲说明',
    fileSize: '2.3 MB',
    format: 'PDF',
    downloadCount: 12800,
  },
  {
    id: 2,
    subject: '高等数学',
    icon: '📐',
    color: '#ff6b35',
    title: '高等数学考试大纲（2024版）',
    desc: '涵盖函数极限、微积分、空间解析几何、无穷级数等考点',
    fileSize: '1.8 MB',
    format: 'PDF',
    downloadCount: 9600,
  },
  {
    id: 3,
    subject: '大学语文',
    icon: '📚',
    color: '#9c27b0',
    title: '大学语文考试大纲（2024版）',
    desc: '文学常识范围、必背篇目、写作要求、阅读理解标准',
    fileSize: '1.5 MB',
    format: 'PDF',
    downloadCount: 8200,
  },
  {
    id: 4,
    subject: '政治理论',
    icon: '📋',
    color: '#e74c3c',
    title: '政治理论考试大纲（2024版）',
    desc: '马原、毛概、思修、近代史纲要等考试范围详解',
    fileSize: '2.1 MB',
    format: 'PDF',
    downloadCount: 7400,
  },
]

/** 电子文库资源 */
export const LIBRARY_ITEMS = [
  {
    id: 11,
    subject: '大学英语',
    icon: '🔤',
    color: '#2a6eff',
    title: '近五年英语真题精编（含详解）',
    desc: '2019-2024年广西专升本英语真题，逐题详细解析',
    tags: ['真题', '热门'],
    fileSize: '5.6 MB',
    format: 'PDF',
  },
  {
    id: 12,
    subject: '高等数学',
    icon: '📐',
    color: '#ff6b35',
    title: '高数必做500题（分章节）',
    desc: '按章节整理的高数精选习题集，每题附详细解答',
    tags: ['习题集', '推荐'],
    fileSize: '8.2 MB',
    format: 'PDF',
  },
  {
    id: 13,
    subject: '大学语文',
    icon: '📚',
    color: '#9c27b0',
    title: '大学语文文学常识速记手册',
    desc: '中国古代文学、现当代文学、外国文学知识点汇总',
    tags: ['速记', '精华'],
    fileSize: '3.4 MB',
    format: 'PDF',
  },
  {
    id: 14,
    subject: '政治理论',
    icon: '📋',
    color: '#e74c3c',
    title: '政治主观题万能答题模板',
    desc: '涵盖各类主观题型答题框架与高频考点话术',
    tags: ['模板', '干货'],
    fileSize: '2.8 MB',
    format: 'PDF',
  },
  {
    id: 15,
    subject: '综合',
    icon: '📝',
    color: '#4caf50',
    title: '专升本全科模拟冲刺卷（12套）',
    desc: '高度仿真模拟试卷，覆盖所有科目，含答题卡模板',
    tags: ['模拟卷', '冲刺'],
    fileSize: '12.5 MB',
    format: 'PDF',
  },
  {
    id: 16,
    subject: '计算机',
    icon: '💻',
    color: '#ff9800',
    title: '计算机基础高频考点精讲',
    desc: 'Office操作、计算机网络、数据结构等核心考点梳理',
    tags: ['计算机', '高频'],
    fileSize: '4.1 MB',
    format: 'PDF',
  },
]

/** 核心知识点 */
export const KNOWLEDGE_ITEMS = [
  {
    id: 21,
    subject: '大学英语',
    icon: '🔤',
    color: '#2a6eff',
    title: '英语核心词汇2000词',
    desc: '按考频排序的核心词汇表，含例句与记忆技巧',
    itemCount: 2000,
    estimatedTime: '30天',
    difficulty: '基础',
  },
  {
    id: 22,
    subject: '高等数学',
    icon: '📐',
    color: '#ff6b35',
    title: '高数公式定理大全',
    desc: '极限、导数、积分、微分方程等全部公式汇总',
    itemCount: 158,
    estimatedTime: '7天',
    difficulty: '基础',
  },
  {
    id: 23,
    subject: '大学语文',
    icon: '📚',
    color: '#9c27b0',
    title: '必背古诗词60首',
    desc: '含全文、译文、赏析、常考名句标注',
    itemCount: 60,
    estimatedTime: '20天',
    difficulty: '适中',
  },
  {
    id: 24,
    subject: '政治理论',
    icon: '📋',
    color: '#e74c3c',
    title: '政治高频考点100条',
    desc: '马原、毛概核心考点浓缩，考前必背',
    itemCount: 100,
    estimatedTime: '14天',
    difficulty: '适中',
  },
  {
    id: 25,
    subject: '管理学',
    icon: '📊',
    color: '#4caf50',
    title: '管理学原理思维导图集',
    desc: '决策、组织、领导、控制四大职能知识框架',
    itemCount: 45,
    estimatedTime: '10天',
    difficulty: '基础',
  },
  {
    id: 26,
    subject: '经济学',
    icon: '💰',
    color: '#607d8b',
    title: '经济学基础概念速查',
    desc: '微观经济学与宏观经济学核心概念一览',
    itemCount: 80,
    estimatedTime: '8天',
    difficulty: '基础',
  },
]